### ISSUE TITLE
How to resolve the Error in building pyDemFoam

### ISSUE THREAD

**Issue by mahwishakram** [jkfurtney/PFC3D_OpenFOAM#13]
Hello,
While building pyDemFoam all the commands go well but at the end to test the working of pyDemFoam the command "python -c "import pyDemFoam; print(pyDemFoam.__version__)" gives following error
"Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mahwish/.local/lib/python2.7/site-packages/pyDemFoam/__init__.py", line 3, in <module>
    from _pyDemFoam import pyDemIcoFoam
ImportError: /home/mahwish/.local/lib/python2.7/site-packages/_pyDemFoam.so: undefined symbol: _ZN4Foam13UIPstreamBase4readERl

Kindly guide me to resolve the error

**Comment by zx-0884** [comment]
I have the same problem. Have you solved it?

**Comment by mahwishakram** [comment]
no i didn't resolved it yet

**Comment by ansel-cat** [comment]
Have you solved it?

**Comment by wobuhui127** [comment]
Have you solved it?

**Comment by wobuhui127** [comment]
Version number issue. I previously operated with other ubuntu version numbers and openfoam version numbers, and the result was the same as you described. However, using the specific version number specified by the blogger, the command "python -c" import pyDemFoam was successfully output; print (pydemfoamo.version) --2022.0109
